function n(id){return parseFloat(document.getElementById(id).value)}
function fmt(x){return Number.isFinite(x)?(Math.abs(x)>=1000?x.toLocaleString(undefined,{maximumFractionDigits:3}):x.toFixed(3).replace(/\.000$/,'')):'—'}
function calcOhm(){let v=n('ohm-v'),i=n('ohm-i'),r=n('ohm-r');if(Number.isFinite(v)&&Number.isFinite(i)){r=v/i}else if(Number.isFinite(v)&&Number.isFinite(r)){i=v/r}else if(Number.isFinite(i)&&Number.isFinite(r)){v=i*r}else{return document.getElementById('ohm-out').textContent='Enter any two values'}document.getElementById('ohm-v').value=Number.isFinite(v)?v:'';document.getElementById('ohm-i').value=Number.isFinite(i)?i:'';document.getElementById('ohm-r').value=Number.isFinite(r)?r:'';document.getElementById('ohm-out').textContent=`V=${fmt(v)} V · I=${fmt(i)} A · R=${fmt(r)} Ω`}
function calcDivider(){const v=n('div-v'),r1=n('div-r1'),r2=n('div-r2'),o=document.getElementById('div-out');if(v>0&&r1>0&&r2>0)o.textContent=`Vout = ${fmt(v*r2/(r1+r2))} V`;else o.textContent='Enter Vin, R1 and R2'}
function ipToInt(ip){return ip.split('.').reduce((a,o)=>(a<<8)+(+o),0)>>>0}function intToIp(i){return[(i>>>24)&255,(i>>>16)&255,(i>>>8)&255,i&255].join('.')}
function calcCIDR(){const s=document.getElementById('cidr').value.trim(),o=document.getElementById('cidr-out');const m=s.match(/^(\d{1,3}(?:\.\d{1,3}){3})\/(\d|[12]\d|3[0-2])$/);if(!m)return o.textContent='Use format 192.168.1.0/24';const oct=m[1].split('.').map(Number);if(oct.some(x=>x>255))return o.textContent='Invalid IPv4 address';const p=+m[2],mask=p===0?0:(0xffffffff<<(32-p))>>>0,network=ipToInt(m[1])&mask,broadcast=(network|(~mask>>>0))>>>0,hosts=p>=31?2**(32-p):Math.max(0,2**(32-p)-2);o.textContent=`Mask ${intToIp(mask)} · Network ${intToIp(network)} · Broadcast ${intToIp(broadcast)} · ${hosts.toLocaleString()} usable hosts`}
const resistorColors=[['Black',0],['Brown',1],['Red',2],['Orange',3],['Yellow',4],['Green',5],['Blue',6],['Violet',7],['Grey',8],['White',9]];
['c1','c2','c3'].forEach(id=>{const s=document.getElementById(id);if(s)resistorColors.forEach(c=>{const o=document.createElement('option');o.value=c[1];o.textContent=c[0];s.appendChild(o)})});
function calcResistor(){const a=+document.getElementById('c1').value,b=+document.getElementById('c2').value,c=+document.getElementById('c3').value;const value=(a*10+b)*10**c;let text=value>=1e6?`${value/1e6} MΩ`:value>=1e3?`${value/1e3} kΩ`:`${value} Ω`;document.getElementById('res-out').textContent=text}
const focus=document.getElementById('focus'),target=document.getElementById('target'),targetOut=document.getElementById('target-out');function updateTarget(){targetOut.textContent=`${target.value} hour${target.value==1?'':'s'}`};target.addEventListener('input',updateTarget);try{const saved=JSON.parse(localStorage.getItem('hb-study')||'{}');if(saved.focus)focus.value=saved.focus;if(saved.target)target.value=saved.target;updateTarget()}catch(e){}
function saveStudy(){localStorage.setItem('hb-study',JSON.stringify({focus:focus.value,target:target.value,updated:new Date().toISOString()}));document.getElementById('saved').textContent='Saved locally ✓';setTimeout(()=>document.getElementById('saved').textContent='',2500)}

const toolboxMarkup=`<section id="expanded-toolbox" class="expanded-toolbox"><div class="section-heading"><div><span class="section-kicker">03.1 / THE TOOLBOX</span><h2>1,000+ Engineering Tools</h2></div><p>Searchable micro-tools covering electrical, electronics, automation, networking, cybersecurity, Linux, programming, data analytics and engineering units. Only the visible page is rendered, so the toolbox stays fast.</p></div><div class="toolbox-controls"><label class="tool-search"><span>⌕</span><input id="tool-search" type="search" placeholder="Search 1,000+ tools..." autocomplete="off"></label><select id="tool-category"></select><span id="tool-summary">Loading toolbox…</span></div><div id="toolbox-app" class="toolbox-grid"></div><div id="tool-page" class="tool-pagination"></div></section><div id="tool-modal" class="tool-modal" aria-hidden="true"><div class="tool-modal-card"><button class="modal-close" onclick="closeMicroTool()">×</button><h2 id="modal-title">Tool</h2><div id="modal-body"></div></div></div>`;
const tb=document.getElementById('toolbench');if(tb)tb.insertAdjacentHTML('afterend',toolboxMarkup);const toolboxScript=document.createElement('script');toolboxScript.src='toolbox.js';document.body.appendChild(toolboxScript);
